name: GitHub Snake Game

on:
  # ─────────────── automatic run every day at 00:00 UTC ───────────────
  schedule:
    - cron: "0 0 * * *"
  # ─────────────── manual trigger from the Actions tab ────────────────
  workflow_dispatch:
  # ─────────────── regenerate when you push to main ───────────────────
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1️⃣ Check out your repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Generate the snake animations
      - name: Build snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: YOUR_GITHUB_USERNAME      # ← change this
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Push the generated files to an `output` branch
      - name: Publish to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "chore: update snake animation [skip ci]"